global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'paas-prometheus@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'app', 'type']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: paas-admins

  # The child route trees.
  routes:
  # This routes performs a regular expression match on alert labels to
  # catch alerts that are related to a list of services.
  - receiver: 'down-pager'
    group_wait: 10s
    match_re:
      service: elasticsearch

# Inhibition rules allow to mute a set of alerts given that another alert is
# firing.
# We use this to mute any warning-level notifications if the same alert is
# already critical.
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']


receivers:
- name: 'paas-admins'
  email_configs:
  - to: 'paas-admins@example.org'
- name: 'down-pager'
  webhook_configs:
  - url: 'http://localhost:1234'
    send_resolved: true
