apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: 2017-06-29T07:06:57Z
    name: prometheus-storage
    namespace: paas-monitoring
    resourceVersion: "5871"
    selfLink: /api/v1/namespaces/paas-monitoring/persistentvolumeclaims/prometheus-storage
    uid: 8a3449f9-5c99-11e7-af5f-82c11eecd0b6
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeName: pv0051
  status:
    accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
    capacity:
      storage: 100Gi
    phase: Bound
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
